version: "3.1"

services:
    iot-agent:
        image: fiware/iotagent-lorawan
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongo-db
        expose:
            - "4061"
        ports:
            - "4061:4061"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4061"
            - "IOTA_REGISTRY_TYPE=mongo-db"
            - "IOTA_MONGO_HOST=mongo-db"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-lorawan"
            - "IOTA_PROVIDER_URL=http://iot-agent:4061"
            - "IOTA_LOG_LEVEL=DEBUG" # The log level of the IoT Agent

    mongo-db:
        image: mongo:3.6
        hostname: mongo-db
        container_name: db-mongo
        expose:
            - "27017"
        ports:
            - "27017:27017"
        command: --bind_ip_all --smallfiles
        volumes:
            - mongo-db:/data

    orion:
        image: fiware/orion
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongo-db
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongo-db

    quantumleap:
        image: smartsdk/quantumleap:0.5
        ports:
          - "8668:8668"
        depends_on:
          - mongo-db
          - orion
          - crate
        environment:
          - CRATE_HOST=crate
          - USE_GEOCODING=True
          - REDIS_HOST=redis
          - REDIS_PORT=6379
    
    crate:
    #    image: crate:3.0.5
        image: crate
    #    command: >
    #      crate -Clicense.enterprise=false 
    #      -Cauth.host_based.enabled=false
    #      -Ccluster.name=democluster 
    #      -Chttp.cors.enabled=true 
    #      -Chttp.cors.allow-origin="*"
        ports:
          # Admin UI
          - "4200:4200"
          # Transport protocol
          - "4300:4300"
        environment:
          - CRATE_HEAP_SIZE=2g
        volumes:
          - cratedata:/data
    
    grafana:
      #image: grafana/grafana:5.4.2
        image: grafana/grafana:latest
        ports:
          - "3000:3000"
    #    environment:
    #      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
        depends_on:
          - crate
    
    redis:
      #image: redis:5.0.3
        image: redis:latest
        ports:
          - "6379:6379"
        volumes:
          - redisdata:/data

volumes:
    mongo-db: ~
    cratedata: ~
    redisdata: ~
